### ISSUE TITLE
java.lang.management not available on Android

### ISSUE THREAD

**Issue by neroux** [oblac/jodd-util#16]
@igr, it would appear as if the newest Android Studio (or one of its libraries) was not too fond of the use of `java.lang.management.ManagementFactory` in `jodd.util.SystemInfo`

https://github.com/oblac/jodd-util/blob/8d7398b8f9b06163c05e54e4efd0719961300aa6/src/main/java/jodd/util/SystemInfo.java#L495

The error message is

    Missing class java.lang.management.ManagementFactory (referenced from: long jodd.util.SystemInfo.getCurrentPID())
    Missing class java.lang.management.RuntimeMXBean (referenced from: long jodd.util.SystemInfo.getCurrentPID())

That seems to be a general issue with that package on Android -> https://stackoverflow.com/a/19595885 and https://github.com/Kotlin/kotlinx.coroutines/issues/959

It's possible to "skip" that error, so it's not a complete show-stopper. Rather a heads-up :)

**Comment by igr** [comment]
Maybe I can just remove that method, as on Java9 there is a new way anyway: long pid = ProcessHandle.current().pid();

**Comment by igr** [comment]
6.2.1. released:)

**Comment by neroux** [comment]
While `ManagementFactory` certainly is an official class, one may argue `ProcessHandle` is even "more" official, as it's dedicated to the process ID. What one should consider is that Jodd currently still supports Java 1.8 and `ProcessHandle` was only introduced with Java 1.9.

That being said, I am not sure if `ProcessHandle` is available on Android either. As long as one does not try to get the process ID, it actually shouldn't be an issue on Android. As mentioned, the message can be skipped, so it was really mostly as information :)
