### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [oblac/jodd-util#18]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@zlase0820) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by neroux** [comment]
An email address is listed on the profile of @igr. However, AFAIK he currently is only intermittently online, so I would not expect an immediate response.

**Comment by neroux** [comment]
Are you referring to #17?
