### ISSUE TITLE
Missing tag for 6.2.2

### ISSUE THREAD

**Issue by pzygielo** [oblac/jodd-util#22]
https://repo.maven.apache.org/maven2/org/jodd/jodd-util/6.2.2/

**Comment by igr** [comment]
Just releasing 6.3.0 :)

**Comment by igr** [comment]
Thank you!

**Comment by pzygielo** [comment]
Thanks for checking.

Given the tag 6.2.2 is still missing in repository, shall I understand it's not possible to mark the sources with one?

**Comment by igr** [comment]
I created a tag: https://github.com/oblac/jodd-util/releases/tag/v6.2.2
Just there is no release on Github. Hope this doesn't cause any problems for you?

**Comment by pzygielo** [comment]
> I created a tag: https://github.com/oblac/jodd-util/releases/tag/v6.2.2 Just there is no release on Github. 

Perfect.

> Hope this doesn't cause any problems for you?

Absolutely not.

Thank you!
